### DISCUSSION TITLE
Brie.fi/ng behind proxy and authentification

### DISCUSSION THREAD

**Discussion by ArnOCP** [holtwick/briefing#149] [Q&A]
Hello Dirk, I discovered your work and it's great, congratulations. I'm just trying to install it behind a reverse proxy, but the video doesn't seem to work? I get the message "waiting for connection".
Additionally, is there an authentication module to initiate the videoconference?
Thank you for the answers.
Kind regards,

**Comment by holtwick** [comment]
Hi

You probably have seen these instructions? https://github.com/holtwick/briefing/blob/master/docs/installation/docker.md

I personally use this reverse proxy https://nginxproxymanager.com/

By default Briefing listens on port 8080. To also use STUN, you need to open its port also, I don't do it via the proxy but directly. This is my `docker-compose.yml`

```
version: '3'

services:
  app:
    build: .
    container_name: briefing
    env_file:
      - .env
    restart: always
    volumes:
      - ./www:/app/www
      - ./dist:/app/dist
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - 3478:3478 #STUN

networks:
  default:
    external:
      name: proxy
```

There is no authentication layer, you may add one yourself. For example the mentionend proxy supports Basic Auth.
